language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

addons:
  firefox: latest
  chrome: stable

before_script:
  - 'php -S 127.0.0.1:8080 &'
  - 'nvm install stable'
  - 'npm install nightwatch selenium-server chromedriver geckodriver'

script:
# - 'node_modules/.bin/nightwatch -e chrome-headless'
  - 'node_modules/.bin/nightwatch -e firefox-headless'
