language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

sudo: required

before_script:
  - 'php -S 127.0.0.1:8080 &'
  - 'nvm install stable'
  - 'npm install casperjs'

script:
  - 'node_modules/casperjs/bin/casperjs test tests.js'
