var lang = {
	page_name: 'TTSS Kraków',
	page_title: 'TTSS Krak\u00F3w - Salidas de tranv\u00EDas en tiempo real',
	page_title_stop_name: 'TTSS Krak\u00F3w - $stop - Salidas de tranv\u00EDas en tiempo real',
	
	map: 'Mapa',
	
	action_close: 'Cerrar',
	action_expand: 'M\u00E1s',
	action_collapse: 'Menos',
	
	enter_query: 'Introduce el nombre de parada o el n\u00FAmero del veh\u00EDculo',
	enter_stop_name_to_begin: 'Introduce el nombre de parada para iniciar',
	select_stop_click_go: 'Elige la parada y haz clic en "Ir"',
	select_stop_type: {
		'b': '$stop (autob\u00FAs)',
		't': '$stop (tranv\u00EDa)',
	},
	stop_name_placeholder: 'Nombre de parada',
	go_button: 'Ir',
	refresh_button: '\u27f3 Actualizar',
	last_refreshed: '\u00DAltima actualizado a las $time',
	loading: 'Cargando...',
	no_data: 'No hay datos',
	
	line_alert_pattern: 'L\u00EDnea $line: $alert',
	
	header_line: 'L\u00EDnea',
	header_direction: 'Direcci\u00F3n',
	header_vehicle: 'Veh\u00EDculo',
	header_time: 'Salida',
	header_delay: 'Retraso',
	header_lines: 'L\u00EDneas',
	header_route: 'Ruta',
	header_carrier: 'Portador',
	header_stop: 'Parada',
	
	boarding_sign: '>>>',
	unknown_sign: '?',
	
	time_now: 'hace un rato',
	time_seconds_prefix: '',
	time_seconds_suffix: ' s',
	time_seconds_ago_prefix: 'hace ',
	time_seconds_ago_suffix: ' s',
	time_minutes_prefix: '',
	time_minutes_suffix: ' min',
	time_minutes_ago_prefix: 'hace ',
	time_minutes_ago_suffix: ' min',
	
	types: {
		'v': 'Veh\u00EDculo',
		'b': 'Autob\u00FAs',
		't': 'Tranv\u00EDa',
		's': 'Parada',
		'sb': 'Parada de autob\u00FAs',
		'st': 'Parada de tranv\u00EDa',
		'p': 'And\u00E9n',
		'pb': 'And\u00E9n de autob\u00FAs',
		'pt': 'And\u00E9n de tranv\u00EDa',
		'l': 'Tu ubicaci\u00F3n',
	},
	
	show_on_map: 'Mostrar en mapa',
	select_feature: 'M\u00E1s de una caracter\u00EDstica elegida encontrada. Elige la correcta:',
	no_results: 'Nada encontrado.',
    departures_for_stop: 'Haz clic para ver las salidas de la parada (y no s\u00F3lo esta parada).',
	departures_for_trams: 'Cambiar a salidas de tranv\u00EDas.',
	departures_for_buses: 'Cambiar a salidas de autobuses.',
	
	tram_type_pattern: '$num $type ($floor)',
	high_floor: 'de piso elevado',
	high_floor_sign: '\u2010\u00A0',
	high_floor_description: 'veh\u00EDculo de piso elevado',
	partially_low_floor: 'parcialmente de piso bajo',
	partially_low_floor_sign: '*\u267F',
	partially_low_floor_description: 'veh\u00EDculo parcialmente de piso bajo',
	low_floor: 'de piso bajo',
	low_floor_sign: '\u267F',
	low_floor_description: 'veh\u00EDculo de piso bajo',
	
	status_departed: 'Ha salido',
	status_stopped: 'En parada',
	status_default: 'De camino',
	status_delayed_4: 'Retrasado 4′+',
	status_delayed_10: 'Retrasado 10′+',
	
    help_click_for_schedule: 'Haz clic en la entrada en la tabla de salidas para ver el programa de veh\u00EDculo.',
	help_legend: 'Leyenda:',
    help_text: 'Tiempos relativos (p.ej. 3 minutos) son llegadas en tiempo real, basadas en datos de ubicaci\u00F3n. Tiempos absolutos (p.ej. 8:01) son salidas previstas, mostradas cuando el veh\u00EDculo no puede ser ubicado. "?" significa un retraso desconocido.',
	help_hover_for_more: 'Pasa sobre el icono para ver m\u00E1s detalles.',
	help_source: 'C\u00F3digo',
	help_license: 'Licencia',
	
	error_title: 'Ha ocurrido un error!',
	error_request_failed: 'Ha ocurrido un error en la solicitud de internet.',
	error_request_failed_status: 'Ha ocurrido este error en la solicitud de internet: $status.',
	error_request_failed_connectivity: 'Ha ocurrido un error en la solicitud de internet - comprueba tu conexi\u00F3n de internet.',
	error_new_version: 'La p\u00E1gina se ha actualizado, recarg\u00E1ndose...',
	error_refresh: 'Error! Actualiza la p\u00E1gina para actualizar los datos.',
	error_location: 'Ha ocurrido un error en ubicar.',
};
